version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: todo_db
    depends_on:
      - mysql
    command: npm run dev

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
