services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: todo_db
    depends_on:
       mysql:
        condition: service_healthy
    volumes:
    - ./app.js:/app/app.js
     - ./public:/app/public

    command: node /app/app.js  

  mysql:
    image: mysql:8
    container_name: todo-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
