---
- name: Copier les fichiers de l'application
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: www-data
    group: www-data
    mode: "{{ item.mode | default('0755') }}"
  with_items:
    - { src: "Dockerfile", dest: "/var/www/todo/Dockerfile" }
    - { src: "docker-compose.yml", dest: "/var/www/todo/docker-compose.yml" }
    - { src: "public/", dest: "/var/www/todo/public", mode: "0755" }
    - { src: "app.js", dest: "/var/www/todo/app.js", mode: "0644" }
    - { src: "db.js", dest: "/var/www/todo/db.js", mode: "0644" }
    - { src: ".env", dest: "/var/www/todo/.env", mode: "0644" }


- name: Installer les dépendances avec npm
  ansible.builtin.shell: npm install
  args:
    chdir: /var/www/todo

- name: Lancer l'application avec Docker Compose
  ansible.builtin.shell: docker-compose up -d
  args:
    chdir: /var/www/todo
