---
- name: Déployer le projet Todo
  hosts: app
  become: true

  vars:
    repo_url: "https://github.com/choeurtis18/tp-ansible"
    project_path: "/var/www/todo"

  tasks:
    - name: Cloner ou mettre à jour le dépôt Git
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ project_path }}"
        version: main
        update: yes

    - name: Installer les dépendances
      ansible.builtin.shell: npm install
      args:
        chdir: "{{ project_path }}"

    - name: Redémarrer l'application avec Docker Compose
      ansible.builtin.shell: docker-compose restart
      args:
        chdir: "{{ project_path }}"
